# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.hoge import Hoge
from openapi_server import util

from openapi_server.models.hoge import Hoge  # noqa: E501

class Fuga(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, hoge=None):  # noqa: E501
        """Fuga - a model defined in OpenAPI

        :param id: The id of this Fuga.  # noqa: E501
        :type id: str
        :param hoge: The hoge of this Fuga.  # noqa: E501
        :type hoge: Hoge
        """
        self.openapi_types = {
            'id': str,
            'hoge': Hoge
        }

        self.attribute_map = {
            'id': 'id',
            'hoge': 'hoge'
        }

        self._id = id
        self._hoge = hoge

    @classmethod
    def from_dict(cls, dikt) -> 'Fuga':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Fuga of this Fuga.  # noqa: E501
        :rtype: Fuga
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Fuga.


        :return: The id of this Fuga.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Fuga.


        :param id: The id of this Fuga.
        :type id: str
        """

        self._id = id

    @property
    def hoge(self):
        """Gets the hoge of this Fuga.


        :return: The hoge of this Fuga.
        :rtype: Hoge
        """
        return self._hoge

    @hoge.setter
    def hoge(self, hoge):
        """Sets the hoge of this Fuga.


        :param hoge: The hoge of this Fuga.
        :type hoge: Hoge
        """

        self._hoge = hoge
