# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.fuga import Fuga
from openapi_server import util

from openapi_server.models.fuga import Fuga  # noqa: E501

class Hoge(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, fuga=None):  # noqa: E501
        """Hoge - a model defined in OpenAPI

        :param id: The id of this Hoge.  # noqa: E501
        :type id: str
        :param fuga: The fuga of this Hoge.  # noqa: E501
        :type fuga: Fuga
        """
        self.openapi_types = {
            'id': str,
            'fuga': Fuga
        }

        self.attribute_map = {
            'id': 'id',
            'fuga': 'fuga'
        }

        self._id = id
        self._fuga = fuga

    @classmethod
    def from_dict(cls, dikt) -> 'Hoge':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Hoge of this Hoge.  # noqa: E501
        :rtype: Hoge
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Hoge.


        :return: The id of this Hoge.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Hoge.


        :param id: The id of this Hoge.
        :type id: str
        """

        self._id = id

    @property
    def fuga(self):
        """Gets the fuga of this Hoge.


        :return: The fuga of this Hoge.
        :rtype: Fuga
        """
        return self._fuga

    @fuga.setter
    def fuga(self, fuga):
        """Sets the fuga of this Hoge.


        :param fuga: The fuga of this Hoge.
        :type fuga: Fuga
        """

        self._fuga = fuga
